Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> def hamming_distance(s, t):
    dh = 0

    for i, c in enumerate(s):
        if c != t[i]:
            dh += 1
 
    return dh

>>> if __name__ == "__main__":

    small_dataset = """
    GAGCCTACTAACGGGAT
    CATCGTAATGACGGCCT
    """

    
>>> large_dataset = """AGCACGCGAAAACCGGCGTTCGATACCTTGACTAATTCGTTTGATACCCCTCTACAGCTGATACCGGATCGAACGTCGCTAGGTCCACCTTAATCTAGCCACATTAACGCACATTGGTAGTGATTGTCACACACTCCGAATCGTAGTTCGATTTCTACGTCAGGTGGAAGGGCCGAGCGTAATGAAACCAAGGTGTGACTTTGCTACGCGCGTGCCTCAATGCGCGTGCGGAGGCCCTACGGTACGTAGGAAATCTACTGATAGAGTCACTTTCTAGCCTGTCCGGGGGACATCAGAAGGCGTGTGTAAATTAAATCTAAATATGTACGCGTAGAGCACTGTTTAAGTGTCGAACGGCACTGCCGTTGGCTGTACGGTTTGCTATGATTTTCGCGCCTGAACTTCACCACTACGGTCGGATACGAGCCCCCTTAGATCTGGATCTGCTTTGAACCCTGTTTCCAGCTGGTCCAGCCTATTGTGCTGCCTTTTAAAGAACCCAAAGTGGAAGCAATGTCATTTGATGATGAATTGCCTTCCGCTACTAGCACACTTAGGACTAGGTATACATCACCAACAATCGAAAAGCGGCTATACTCTTTGGGTTATTCTCATAGCTATCTTTTACGATTAACCGGAACTGTACACAGGACACGCACTCGTTGCAAGGCATTCTGCGTAGTGGGAAGCTCATATACAAGAGACAATCACGCCTGTCACAGTTTGTCGTATAGCCGTTACTACTGTTTTTCCCAAATGGTGACGTGGGCCTCTGATGCATAGCTCTTTTGCCCTTACCACGGTTTGTAGTTAAGAGTAATACGTTGTACACAGGCGATGGTCTCTTGTGTTCGGCTTTTGGTGCCTGTTGGGAGAATTCGGGGATAGACAGAACGTATAACTTACCTAATGACGGGCAAATTATTGGTTTAGGCTTGGCCGTATGATCGGGGTGAAAGACGACGCATACGC
TACTAGGTCATTCTAGGGTTCTACATCCGGCCAACGCCGTGTGAATCCCCTTGCGGAATCGTTCCATATCTCATCCCTCTGCGACCACCCCGAGGTCGAAATATGCGCCCGCCTTTCAATGAATTGGCCCGTACCTTCAACGATAAAAAGACCGTTAGGGCATAGGCAGGCGGTGTGAGAAATCAGACAATTGTATGTTTGTGTTCCGTATGCAGAGCGAATCGCCTAGACATGTTCATTAGTGCCCTGGAGTGGTTGATATATGATTAATATCGCTCGTGTCTGGGCGACTACGGAAGGAACGTCTTCCTCTCAAGTTTATAGGTTCCCACTATACATCTTTTTTGCAAAGAAAGGTACGGCAATGGGATCCACCGTTCGCTTTACTATTGGAGGCTTTACGTTATGAGCAGACGGTGGTCGCACTCCCCAAAGAAGTTGACCTGCACGGGCACCTTTTCCAGCCGAGTCCTTGCCATTACAATGCATGTGATCCAAGTAATTGACTCCGGAAGGCCATCAGATTATGAATGGTCTTGTACTACCACGACTCTCCGGTAGAGCAATAATTCGGAATAAAGCCACCTACATATTTATAATCTGTGGCATATTTCTACCAACCAATCACGATTAACAACATCTCCGGACTGCAGACGCATTCCAAGAAATGCCAACTGAGGCATGGGACGAGAAAATAGTACTGACAGTTGCCCCGAGCACCTTTCATTAATGAACTGTCAATAGAGTTCGGCATGTAACGAGGCGTAGGCATGCAGTTGGGTAGTGTGATGGCATGCCTGCCATACGGCAAATTTACGTAAAGTAGCTACGTAGCCAACCCTCTGTTGGGGTCGTCGTTCAGTCAACGTTGCTAGGGATCCGGGTTGGGAATAATATATGAGAAAGTTATCGCCGGATGTGGCAATTATTATGTTTCTGTTCCATGATCTGCTTGATTGAGGACCCATTAGA"""
>>>  s, t = large_dataset.split()
 
SyntaxError: unexpected indent
>>> s, t = large_dataset.split()
>>> dist = hamming_distance(s, t)
>>> print dist
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(dist)?
>>> print (dist)
508
>>> 
